// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzjosiA7dZof6VM5IwscMdip8PnRPDAhc',
    appId: '1:329500099737:web:85f41c631cfbdca5812408',
    messagingSenderId: '329500099737',
    projectId: 'life-drop-521d5',
    authDomain: 'life-drop-521d5.firebaseapp.com',
    storageBucket: 'life-drop-521d5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDYTI3r8VC4mx3Ko4hZB2ibUvtDFFhzv8',
    appId: '1:329500099737:android:06a0ab3e405a0a93812408',
    messagingSenderId: '329500099737',
    projectId: 'life-drop-521d5',
    storageBucket: 'life-drop-521d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsh4956N50SIAthVeTWl-L7ZR8uL67Jms',
    appId: '1:329500099737:ios:f38b8071dce58977812408',
    messagingSenderId: '329500099737',
    projectId: 'life-drop-521d5',
    storageBucket: 'life-drop-521d5.firebasestorage.app',
    iosBundleId: 'com.example.lifeDrop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsh4956N50SIAthVeTWl-L7ZR8uL67Jms',
    appId: '1:329500099737:ios:f38b8071dce58977812408',
    messagingSenderId: '329500099737',
    projectId: 'life-drop-521d5',
    storageBucket: 'life-drop-521d5.firebasestorage.app',
    iosBundleId: 'com.example.lifeDrop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzjosiA7dZof6VM5IwscMdip8PnRPDAhc',
    appId: '1:329500099737:web:fb82e2af4c0ead4a812408',
    messagingSenderId: '329500099737',
    projectId: 'life-drop-521d5',
    authDomain: 'life-drop-521d5.firebaseapp.com',
    storageBucket: 'life-drop-521d5.firebasestorage.app',
  );
}
